### ISSUE TITLE
Loading error: No module named 'Utils'

### ISSUE THREAD

**Issue by Harvester62** [toriato/stable-diffusion-webui-wd14-tagger#11]
The following error message is displayed in the SD Web UI console during startup:

Error loading script: tagger.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger.py", line 22, in <module>
    import Utils.dbimutils as dbimutils
ModuleNotFoundError: No module named 'Utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 13, in <module>
    from tagger import interrogate_tags, postprocess_tags
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger.py", line 24, in <module>
    raise Exception(
Exception: Utils.dbimutils not found, did you follow the instruction?

Current SD Web UI version installed locally is Hash https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/47a44c7e421b98ca07e92dbf88769b04c9e28f86

Local system is Windows 10 64bit, 32GB RAM, Nvidia GTX1070 8GB VRAM, Nvidia Driver v526.98, CUDA v12.0

webui-user.bat command line arguments as follows:
set COMMANDLINE_ARGS=--xformers --opt-split-attention --disable-safe-unpickle --api --deepdanbooru --allow-code --administrator --medvram

**Comment by toriato** [comment]
Did you follow the installation section of README?
you need to download and extract model and source file first.
https://github.com/toriato/stable-diffusion-webui-wd14-tagger#installation

**Comment by Harvester62** [comment]
Sorry, I didn't follow the entire installation process. Now I did it and I don't get any error messages. One question, are these messages relevant or just warnings or for information?

2022-11-20 16:26:53.756455: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-20 16:26:54.175859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5698 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1

Thank you.

**Comment by toriato** [comment]
Next to timestamp, 'I' indicates that it is an information log.
The first log means that tensorflow can use CPU instructions that are displayed(`AVX`, `AVX2`) when running tasks that require high performance.
The second means that tensorflow has found GPU and initialized them to be available.
So yes, the above logs are safe to ignore :)

**Comment by Harvester62** [comment]
Thank you very much! I will soon translate your Extension in Italian language, not everything, but surely all the main operations/functions. The list of tags is too complex and long, and I think they should stay in English language. I think you can close this "bug" report.
