### ISSUE TITLE
"Escape brackets" will result in an error.

### ISSUE THREAD

**Issue by tsukimiya** [toriato/stable-diffusion-webui-wd14-tagger#14]
I use "Escape brackets" option.
The following error occurred.

```
Error completing request
Arguments: (None, '/notebooks/train_data/my_pict/*', False, '/notebooks/train_data/my_pict/', 'Flatfile', 0.7, 'breasts', False, True, True, '0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||', True) {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py", line 198, in give_me_the_tags
    processed_tags = postprocess_tags(tags, *postprocess_opts)
  File "/notebooks/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger.py", line 121, in postprocess_tags
    new_tag = tag.replace(tag_escape_pattern, r'\\\1')
TypeError: replace() argument 1 must be str, not re.Pattern

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

Is there anything I should check?

**Comment by toriato** [comment]
I think I solved it, can you check if the error still exists?

**Comment by tsukimiya** [comment]
Confirmed resolution.
Thank you for your response!
