### ISSUE TITLE
Tuple index out of range error

### ISSUE THREAD

**Issue by trihardseven** [toriato/stable-diffusion-webui-wd14-tagger#22]
Getting this error after updating to latest commit:
```
To create a public link, set `share=True` in `launch()`.`
Downloading Waifu Diffusion tagger model files from SmilingWolf/wd-v1-4-vit-tagger
Loading Waifu Diffusion tagger model from C:\Users\Rance\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc
2022-12-06 15:35:25.984105: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-06 15:35:26.616247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 19056 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:29:00.0, compute capability: 8.6
Error completing request
Arguments: (<PIL.Image.Image image mode=RGB size=956x968 at 0x25F4373D690>, '', False, '', '[name].[output_extension]', 'ignore', False, 'wd14', 0.35, '', '', False, False, True, '0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||', False) {}
Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 295, in give_me_the_tags
    ratings, tags = interrogator.interrogate(image)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 218, in interrogate
    self.load()
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 193, in load
    self.model = tf.keras.models.load_model(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 45, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: file is too short to be an sstable

Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

**Comment by SmilingWolf** [comment]
> ```
> tensorflow.python.framework.errors_impl.OpError: file is too short to be an sstable
> ```

This error seems to mean one of the model files could be truncated.
Try wiping ``C:\Users\Rance\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc`` and let it download the model again.

**Comment by trihardseven** [comment]
Did that. Same error though.

```
Downloading: 100%|████████████████████████████████████████████████████████████████| 3.81M/3.81M [00:02<00:00, 1.30MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 328k/328k [00:00<00:00, 713kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 13.8k/13.8k [00:00<00:00, 13.8MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 365M/365M [08:08<00:00, 749kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 174k/174k [00:00<00:00, 422kB/s]
Loading Waifu Diffusion tagger model from C:\Users\Rance\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc
2022-12-06 23:54:33.343392: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-06 23:54:34.046237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 18972 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:29:00.0, compute capability: 8.6
Error completing request
Arguments: (<PIL.Image.Image image mode=RGB size=640x960 at 0x2AE384697B0>, '', False, '', '[name].[output_extension]', 'ignore', False, 'wd14', 0.35, '', '', False, False, True, '0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||', False) {}
Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 295, in give_me_the_tags
    ratings, tags = interrogator.interrogate(image)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 218, in interrogate
    self.load()
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 193, in load
    self.model = tf.keras.models.load_model(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 45, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: file is too short to be an sstable

Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

```

**Comment by SmilingWolf** [comment]
Could you provide the output of `pip freeze` from within the webui venv, list of extensions if you have any other installed, and webui commit hash?

**Comment by sashasubbbb** [comment]
got the same problem after last update, reinstall didn't help. don't really think it's conflicting with something, but anyway
Extensions:
![image](https://user-images.githubusercontent.com/60400449/206265173-5e3ac35c-3eff-4d2b-92b2-9313a2005292.png)
pip freeze: https://pastebin.com/GzWgbv6L
Latest commit: hash commit 44c46f0ed395967cd3830dd481a2db759fda5b3b

**Comment by lendrick** [comment]
Same issue here.

Doesn't look like it's being caused by any of the extensions, because I tried disabling all of the other ones.

Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b 
![Screenshot 2022-12-07 at 15-51-13 Stable Diffusion](https://user-images.githubusercontent.com/311338/206293241-4ff3ad95-a0f2-455a-b560-f6ac6d3bc062.png)
pip freeze: https://pastebin.com/7cF4ZbaN

**Comment by toriato** [comment]
I removed the cache and PIP package from my Windows and Linux environment and tested it after clean installation, but this bug could not be reproduced.

And the code itself doesn't seem to be a problem. Is there a problem with the HuggingFace?

I'm trying to find a way to fix it. If you need to use it right now, use the https://github.com/toriato/stable-diffusion-webui-wd14-tagger/commit/4a9cd4fadc625e4a6a3dcddb2dbeb98645125ef1.  
also in @sneed-formerly-chuck's reply, the file in MEGA is an outdated model. But it works right now, so you can follow this method instead.

**Comment by SmilingWolf** [comment]
I've been trying to break my own venv, trying various versions of Tensorflow between 2.9 - 2.11 (the models were trained using TF 2.10.0), redownloading the weights from HF multiple times, etc. Yet so far, I haven't managed to reproduce the error.

Assuming something went wrong with the serialization of the model (yet most users seem to be ok?), could anybody with a broken setup try and put this file ([saved_model.zip](https://github.com/toriato/stable-diffusion-webui-wd14-tagger/files/10199495/saved_model.zip)) in the `C:\Users\(your username here)\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc` folder and try again?

Mind you: all other files MUST be the ones from HuggingFace, not the ones from the MEGA zip.

**Comment by a1270** [comment]
> I've been trying to break my own venv, trying various versions of Tensorflow between 2.9 - 2.11 (the models were trained using TF 2.10.0), redownloading the weights from HF multiple times, etc. Yet so far, I haven't managed to reproduce the error.
> 
> Assuming something went wrong with the serialization of the model (yet most users seem to be ok?), could anybody with a broken setup try and put the `saved_model.pb` from this: [saved_model.zip](https://github.com/toriato/stable-diffusion-webui-wd14-tagger/files/10199495/saved_model.zip) in the `C:\Users\(your username here)\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc` folder and try again?
> 
> Mind you: all other files MUST be the ones from HuggingFace, not the ones from the MEGA zip.

Just replacing that one file didn't work but manually copying all the blob files to the correct locations and renaming them to the proper filenames did in fact work. Symlinks on windows are rather new so there may be conflicting registry settings. Or windows is just being windows.

Note that copying a file named the same as symlink seems to send it to the great beyond. It doesn't replace the symlink with the file.

**Comment by SmilingWolf** [comment]
That's it! @a1270 you da man!

So all the users with problems are launching a command shell as admins, HF hub is creating symlinks, and subsequent reads from TF/Keras in load_model fail to follow the symlink back to the original file.
This leads to failure to load the model, failure to run predictions (honestly could have used some try/catch during model loading, my bad), returning no predictions at all, and finally to the Tuple index error that got us all reuinited here.

Meanwhile, I was launching the shell as a normal user, so no symlink, because HF hub was downloading files right into the final directory as per https://huggingface.co/docs/huggingface_hub/how-to-cache.

So the immediate fix is to NOT run the shell as Administrator.
Next up is how to force TF/Keras to honor symlinks.

**Comment by SmilingWolf** [comment]
Did some more digging:
- this bug is linked to https://github.com/tensorflow/tensorflow/issues/57685
- it is has been fixed by https://github.com/tensorflow/tensorflow/pull/58440
- that fix is included in tf-nightly, which will at some point become tensorflow v2.12.0

So, two solutions:
- either stop running your cmd prompt as Administrator (you lose the possiblity of using symlinks)
- or install tf-nightly (until v2.12.0 is out, of course) and expect other bugs, atop of the fact that GPU on Windows is officially unsupported since tf v2.11.0 -> all models are going to run on CPU, unless you feel like messing with [TF DirectML](https://github.com/microsoft/tensorflow-directml-plugin)

There's also the possibility of completely forgoing TF's nonsense and switch to ONNXRuntime, but you lose access to the official DeepDanbooru models and have to rely on third party's conversions.
As far as my models are concerned, ONNX versions are "officially" supported, in that I already use them for inference in other settings and will upload them together with the TF models on HF Hub.
This one is up to @toriato of course.

**Comment by toriato** [comment]
Of course I don't mind using ONNX. However, converting DeepDanbooru to ONNX is an individual model maker's choice, and explaining how to convert it to users will be too complicated.

So I think it would be better to support ONNX additionally.

Using Torch, Tensorflow and ONNX together in one program is a bit silly, but I think this is the best.

Thank you all for your help! If there is anything that can be improved, don't hesitate to let me know!

**Comment by trihardseven** [comment]
> Ok, so I seemed to have found a solution to the first problem! Just DM me and I'll send you the ans-I'm just kidding. First, download the tagger model from here: https://mega.nz/file/ptA2jSSB#G4INKHQG2x2pGAVQBn-yd_U5dMgevGF8YYM9CR_R1SY
> 
> After you unpack it, you'll want the files:
> 
> * 2022_0000_0899_6549\selected_tags.csv
> * networks\ViTB16_11_03_2022_07h05m53s\keras_metadata.pb
> * networks\ViTB16_11_03_2022_07h05m53s\saved_model.pb
> * networks\ViTB16_11_03_2022_07h05m53s\variables\variables.data-00000-of-00001
> * networks\ViTB16_11_03_2022_07h05m53s\variables\variables.index
> 
> Next, navigate to your `C:\Users\(your username here)\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger\snapshots\0b4934b152c4a15ed726ec89c6bc7e2ab41d9fbc` folder and replace the three corresponding files there with the ones you just grabbed, then do the same on the `\variables` subfolder with the other two files
> 
> Now run the webui bat, and it should work! At least it did for me, so I hope it does for you too.

file got removed...



> That's it! @a1270 you da man!
> 
> So all the users with problems are launching a command shell as admins, HF hub is creating symlinks, and subsequent reads from TF/Keras in load_model fail to follow the symlink back to the original file. This leads to failure to load the model, failure to run predictions (honestly could have used some try/catch during model loading, my bad), returning no predictions at all, and finally to the Tuple index error that got us all reunited here.
> 
> Meanwhile, I was launching the shell as a normal user, so no symlink, because HF hub was downloading files right into the final directory as per https://huggingface.co/docs/huggingface_hub/how-to-cache, and no problems.
> 
> So the immediate fix is to NOT run the shell as Administrator. Next up is how to force TF/Keras to honor symlinks.
> 
> EDIT: narrowed it down to `variables/variables.index`. If only this one file is copied instead of symlinked, everything else works as expected.

Where can I find this variables file?

**Comment by trihardseven** [comment]
Found the file and it worked! I will say I don't run the webUI as admin, so I'm not sure what caused this issue.

**Comment by toriato** [comment]
I modified it to use ONNX as recommended by @SmillingWolf. If it works well, I'll close the issue.

**Comment by rrweller** [comment]
I am still having this issue and the above linked files are no longer available
