### ISSUE TITLE
Bug: Unable to retrieve path in preload.py upon Extension tab installation

### ISSUE THREAD

**Issue by DeeVeeAkkun** [toriato/stable-diffusion-webui-wd14-tagger#36]
No idea what to do here. The other issue thread suggested some solutions, but none of them worked. Anyone got any idea?

Error executing callback ui_tabs_callback for D:\diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py
Traceback (most recent call last):
  File "D:\diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 85, in ui_tabs_callback
    res += c.callback() or []
  File "D:\diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 352, in on_ui_tabs
    interrogator_names = refresh_interrogators()
  File "D:\diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 45, in refresh_interrogators
    shared.cmd_opts.deepdanbooru_projects_path,
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

**Comment by toriato** [comment]
Please provide the output of `git rev-parse HEAD`

**Comment by toriato** [comment]
If the issue has been resolved, please close it. Thanks for letting me know about the bug!

**Comment by spedman334** [comment]
The issue has been resolved for me, thanks.

**Comment by cbstyle** [comment]
same problem, how to solve it ? thanks

**Comment by jiajie999** [comment]
same +1

**Comment by xionglian** [comment]
same +1

**Comment by greenfire2012** [comment]
same +1
