### ISSUE TITLE
'Namespace' object has no attribute 'deepdanbooru_projects_path'

### ISSUE THREAD

**Issue by CaptainGodual** [toriato/stable-diffusion-webui-wd14-tagger#57]
I recently installed the tagger using the install extensions from url feature of SD Webui,

Upon restarting the ui I get this error for the Tagger. 

`Error executing callback ui_tabs_callback for /home/paperspace/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py
Traceback (most recent call last):
  File "/home/paperspace/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/home/paperspace/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/ui.py", line 329, in on_ui_tabs
    interrogator_names = utils.refresh_interrogators()
  File "/home/paperspace/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/utils.py", line 61, in refresh_interrogators
    for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'`

What could be causing this? I am not sure if it is a bug or what.

**Comment by CaptainGodual** [comment]
This was unreproducible by myself a second time, so I am assuming something just didn't install right, after a reinstall this issue is gone.
