### ISSUE TITLE
ValueError: Number of output components does not match number of values returned from from function f

### ISSUE THREAD

**Issue by Amber-Xxx** [toriato/stable-diffusion-webui-wd14-tagger#71]
Traceback (most recent call last):
  File "/Users/yjx/Desktop/SDAI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yjx/Desktop/SDAI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/yjx/Desktop/SDAI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/yjx/Desktop/SDAI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by raidenxu** [comment]
me 2

**Comment by o0arthur0o** [comment]
me 2

**Comment by xcreateadmin** [comment]
Getting same on Mac M1 SD Web UI Local Installation

**Comment by charleybin** [comment]
+ 1
Mac M2 Max

**Comment by nbdy-coder** [comment]
Same error on mac m1

**Comment by AI-Based-Businesses** [comment]
I'm getting the exact same error when trying to use Deforum for the first time, but everything else works fine.

**Comment by ZhelenZ** [comment]
same error on mac m2

**Comment by canoneosc70** [comment]
same error also

**Comment by Dice-ksan** [comment]
The same thing happened to me as well. I hope some genious to solve this.

**Comment by Tedrer** [comment]
The same for me

**Comment by vjsaw** [comment]
same

**Comment by NiggyPop** [comment]
samesies.... has there been a solution for this?

**Comment by Tedrer** [comment]
Ok guys. I discovered that it is happen after out of memory in the GPU. Try to decrease the output resolution. That's in my area, hope it will help for u2.

**Comment by canoneosc70** [comment]
here my soltuion after a long period of searching , all what you have to do is change your model, here the link for the model 
https://civitai.com/images/293422?period=AllTime&sort=Most+Reactions&view=categories&modelVersionId=20937&modelId=11718&postId=78726

**Comment by shiranui1994** [comment]
me2, i cant load anything from extension_available.

**Comment by ojama** [comment]
same on iMac with intel cpu

**Comment by lolpopkk** [comment]
> same on iMac with intel cpu
same here
