### ISSUE TITLE
Tagger Tab does not appear. Failed on startup details below.

### ISSUE THREAD

**Issue by DoctorBlackZ33** [toriato/stable-diffusion-webui-wd14-tagger#80]
So i installed the Extension from URL and then i restarted the UI. It is to note i use the this version of the webUI but it works the same (https://github.com/vladmandic/automatic). I got somewhat of a log and stuff but i dont get what i should do now.

12:54:34-239563 INFO     Installing extension: https://github.com/toriato/stable-diffusion-webui-wd14-tagger into
                         C:\ai\automatic\extensions\stable-diffusion-webui-wd14-tagger
12:54:55-411313 INFO     Server shutdown requested
12:55:06-467593 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "C:\ai\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
12:55:08-513442 INFO     Server will restart
12:55:08-927070 INFO     Server restarting...
12:55:12-232533 INFO     Libraries loaded
12:55:12-244437 INFO     Available models: models\Stable-diffusion 13
ControlNet v1.1.150
Image Browser: ImageReward is not installed, cannot be used.
[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
12:55:13-349488 INFO     Loading theme: black-orange
[text2prompt] Loading database with name "all-mpnet-base-v2 : danbooru_strict"...
[text2prompt] Database loaded
12:55:15-100394 ERROR    executing callback:
                         C:\ai\automatic\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py
                         ui_tabs_callback: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\ai\automatic\modules\script_callbacks.py:151 in ui_tabs_callback                                                 │
│                                                                                                                     │
│   150 │   │   try:                                                                                                  │
│ > 151 │   │   │   res += c.callback() or []                                                                         │
│   152 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ C:\ai\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:329 in on_ui_tabs                        │
│                                                                                                                     │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                           │
│ > 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                    │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                │
│                                                                                                                     │
│ C:\ai\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py:70 in refresh_interrogators           │
│                                                                                                                     │
│   69 │                                                                                                              │
│ > 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                        │
│   71 │   │   if not path.is_dir():                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'
Running on local URL: 

To create a public link, set `share=True` in `launch()`.
12:55:16-210458 INFO     Local URL: http:///
12:55:16-211945 INFO     API Docs: http:///docs
12:55:16-213434 INFO     Initializing middleware
Loading weights: models\Stable-diffusion\-- --------------------------------- 0.1/2.1 GB 0:00:00
12:55:17-515111 INFO     Creating model from config: C:\ai\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
12:55:18-805206 INFO     Loading VAE weights specified in settings: cached 
12:55:19-933109 INFO     Applying scaled dot product cross attention optimization
12:55:19-955925 INFO     Model loaded in 3.7s (load=1.2s create=0.5s apply=0.8s vae=0.1s move=1.0s)
12:55:20-533269 INFO     Startup time: 8.3s (scripts=1.0s opts onchange=0.1s ui=2.7s start=0.2s scripts
                         app_started_callback=0.1s checkpoint=4.3s)
12:55:20-539221 INFO     Memory used: 31.4 total: 47.92

so i deleted model names and localhosts but the rest is about the thing. i can program myself but i dont get what I did wrong. can someone make sense of this? would appreciate this thanks in advance

**Comment by throwaway1234987** [comment]
I dug into the startup code and looked at the Stable Diffusion webui a bit.

I was able to fix this by specifying the path myself on launch with this argument: `--deepdanbooru-projects-path=models/deepdanbooru`. Of course your model path may or may not vary. Hope this helps.
